# Generated by Django 3.1.2 on 2020-10-27 09:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lob_name', models.CharField(max_length=150, unique=True, verbose_name='Nombre campaña')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lob',
                'verbose_name_plural': "Lob's",
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del cargo')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=30, unique=True, verbose_name='Cédula')),
                ('first_name', models.CharField(max_length=30, verbose_name='Primer nombre')),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo nombre')),
                ('first_last_name', models.CharField(max_length=30, verbose_name='Primer apellido')),
                ('second_last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo apellido')),
                ('gender', models.CharField(max_length=15, verbose_name='Género')),
                ('birth_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('avaya_login', models.CharField(max_length=7, verbose_name='Login de avaya')),
                ('ccms_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de ccms')),
                ('slack_id', models.CharField(max_length=20, verbose_name='id de usuario en slack')),
                ('dtvpan_user', models.CharField(max_length=50, null=True, verbose_name='Usuario dtvpan')),
                ('profile_picture', models.ImageField(upload_to='img/profile_pictures/%Y/%m/%d')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('date_hired', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de contratación')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lob', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brain.lob')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brain.agents', verbose_name='Jefe inmediato')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brain.position', verbose_name='Cargo del empleado')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['id'],
            },
        ),
    ]
