# Generated by Django 3.1.2 on 2020-10-27 03:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(default='Agent', max_length=60, verbose_name='Cargo')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('login', models.CharField(max_length=7, unique=True, verbose_name='login')),
                ('LOB', models.PositiveIntegerField(verbose_name='LOB id')),
                ('slack_id', models.CharField(max_length=20, unique=True, verbose_name='Id usuario slack')),
                ('ccms_id', models.CharField(blank=True, max_length=10, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('gender', models.CharField(max_length=1, verbose_name='Sexo')),
                ('state', models.BooleanField(default=True)),
                ('employee_since', models.DateField(default=datetime.datetime.now, verbose_name='Fecha contratación')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robotin.position')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['id'],
            },
        ),
    ]
