# Generated by Django 3.1.2 on 2020-10-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_name',
            field=models.CharField(default='Agent', max_length=60, unique=True, verbose_name='Cargo'),
        ),
    ]
